// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: definitions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addField = `-- name: AddField :one
WITH inserted AS (
    INSERT INTO resource_fields
      (resource_definition_id, key, label, hint, data_type, required, is_secret, sort_order)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, resource_definition_id, key, label, hint, data_type, required, is_secret, sort_order
), touched AS (
    UPDATE resource_definitions rd
    SET updated_at = clock_timestamp()
    FROM inserted i
    WHERE rd.id = i.resource_definition_id
    RETURNING rd.id
)
SELECT i.id, i.resource_definition_id, i.key, i.label, i.hint, i.data_type, i.required, i.is_secret, i.sort_order
FROM inserted i
JOIN touched t ON t.id = i.resource_definition_id
`

type AddFieldParams struct {
	ResourceDefinitionID uuid.UUID `json:"resource_definition_id"`
	Key                  string    `json:"key"`
	Label                string    `json:"label"`
	Hint                 string    `json:"hint"`
	DataType             string    `json:"data_type"`
	Required             bool      `json:"required"`
	IsSecret             bool      `json:"is_secret"`
	SortOrder            int32     `json:"sort_order"`
}

type AddFieldRow struct {
	ID                   uuid.UUID `json:"id"`
	ResourceDefinitionID uuid.UUID `json:"resource_definition_id"`
	Key                  string    `json:"key"`
	Label                string    `json:"label"`
	Hint                 string    `json:"hint"`
	DataType             string    `json:"data_type"`
	Required             bool      `json:"required"`
	IsSecret             bool      `json:"is_secret"`
	SortOrder            int32     `json:"sort_order"`
}

func (q *Queries) AddField(ctx context.Context, arg AddFieldParams) (AddFieldRow, error) {
	row := q.db.QueryRow(ctx, addField,
		arg.ResourceDefinitionID,
		arg.Key,
		arg.Label,
		arg.Hint,
		arg.DataType,
		arg.Required,
		arg.IsSecret,
		arg.SortOrder,
	)
	var i AddFieldRow
	err := row.Scan(
		&i.ID,
		&i.ResourceDefinitionID,
		&i.Key,
		&i.Label,
		&i.Hint,
		&i.DataType,
		&i.Required,
		&i.IsSecret,
		&i.SortOrder,
	)
	return i, err
}

const createDefinition = `-- name: CreateDefinition :one
INSERT INTO resource_definitions (key, name, description, icon)
VALUES ($1, $2, $3, $4) RETURNING id, key, name, description, icon, status, created_at, updated_at
`

type CreateDefinitionParams struct {
	Key         string `json:"key"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
}

func (q *Queries) CreateDefinition(ctx context.Context, arg CreateDefinitionParams) (ResourceDefinition, error) {
	row := q.db.QueryRow(ctx, createDefinition,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Icon,
	)
	var i ResourceDefinition
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefinition = `-- name: GetDefinition :one
SELECT id, key, name, description, icon, status, created_at, updated_at FROM resource_definitions WHERE id = $1
`

func (q *Queries) GetDefinition(ctx context.Context, id uuid.UUID) (ResourceDefinition, error) {
	row := q.db.QueryRow(ctx, getDefinition, id)
	var i ResourceDefinition
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefinitionByKey = `-- name: GetDefinitionByKey :one
SELECT id, key, name, description, icon, status, created_at, updated_at FROM resource_definitions WHERE key = $1
`

func (q *Queries) GetDefinitionByKey(ctx context.Context, key string) (ResourceDefinition, error) {
	row := q.db.QueryRow(ctx, getDefinitionByKey, key)
	var i ResourceDefinition
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceField = `-- name: GetResourceField :one
SELECT id, resource_definition_id, key, label, hint, data_type, required, is_secret, sort_order FROM resource_fields
WHERE id = $1 AND resource_definition_id = $2
FOR UPDATE
`

type GetResourceFieldParams struct {
	FieldID              uuid.UUID `json:"field_id"`
	ResourceDefinitionID uuid.UUID `json:"resource_definition_id"`
}

func (q *Queries) GetResourceField(ctx context.Context, arg GetResourceFieldParams) (ResourceField, error) {
	row := q.db.QueryRow(ctx, getResourceField, arg.FieldID, arg.ResourceDefinitionID)
	var i ResourceField
	err := row.Scan(
		&i.ID,
		&i.ResourceDefinitionID,
		&i.Key,
		&i.Label,
		&i.Hint,
		&i.DataType,
		&i.Required,
		&i.IsSecret,
		&i.SortOrder,
	)
	return i, err
}

const listDefinitions = `-- name: ListDefinitions :many
SELECT id, key, name, description, icon, status, created_at, updated_at FROM resource_definitions ORDER BY name
`

func (q *Queries) ListDefinitions(ctx context.Context) ([]ResourceDefinition, error) {
	rows, err := q.db.Query(ctx, listDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceDefinition
	for rows.Next() {
		var i ResourceDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefinitionsWithCounts = `-- name: ListDefinitionsWithCounts :many
SELECT rd.id, rd.key, rd.name, rd.description, rd.icon, rd.status, rd.created_at, rd.updated_at,
       count(rf.id)::int AS field_count,
       count(rf.id) FILTER (WHERE rf.is_secret)::int AS secret_count
FROM resource_definitions rd
LEFT JOIN resource_fields rf ON rf.resource_definition_id = rd.id
GROUP BY rd.id
ORDER BY rd.name
`

type ListDefinitionsWithCountsRow struct {
	ID          uuid.UUID `json:"id"`
	Key         string    `json:"key"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Icon        string    `json:"icon"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	FieldCount  int32     `json:"field_count"`
	SecretCount int32     `json:"secret_count"`
}

func (q *Queries) ListDefinitionsWithCounts(ctx context.Context) ([]ListDefinitionsWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listDefinitionsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDefinitionsWithCountsRow
	for rows.Next() {
		var i ListDefinitionsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FieldCount,
			&i.SecretCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFields = `-- name: ListFields :many
SELECT id, resource_definition_id, key, label, hint, data_type, required, is_secret, sort_order FROM resource_fields WHERE resource_definition_id = $1
ORDER BY sort_order, key
`

func (q *Queries) ListFields(ctx context.Context, resourceDefinitionID uuid.UUID) ([]ResourceField, error) {
	rows, err := q.db.Query(ctx, listFields, resourceDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceField
	for rows.Next() {
		var i ResourceField
		if err := rows.Scan(
			&i.ID,
			&i.ResourceDefinitionID,
			&i.Key,
			&i.Label,
			&i.Hint,
			&i.DataType,
			&i.Required,
			&i.IsSecret,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeField = `-- name: RemoveField :one
WITH deleted AS (
    DELETE FROM resource_fields rf
    WHERE rf.id = $1
      AND rf.resource_definition_id = $2
    RETURNING rf.resource_definition_id
), touched AS (
    UPDATE resource_definitions rd
    SET updated_at = clock_timestamp()
    FROM deleted d
    WHERE rd.id = d.resource_definition_id
    RETURNING rd.id
)
SELECT count(*)::bigint
FROM deleted d
LEFT JOIN touched t ON t.id = d.resource_definition_id
`

type RemoveFieldParams struct {
	FieldID              uuid.UUID `json:"field_id"`
	ResourceDefinitionID uuid.UUID `json:"resource_definition_id"`
}

func (q *Queries) RemoveField(ctx context.Context, arg RemoveFieldParams) (int64, error) {
	row := q.db.QueryRow(ctx, removeField, arg.FieldID, arg.ResourceDefinitionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setDefinitionStatus = `-- name: SetDefinitionStatus :one
UPDATE resource_definitions SET status = $2, updated_at = now()
WHERE id = $1 RETURNING id, key, name, description, icon, status, created_at, updated_at
`

type SetDefinitionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetDefinitionStatus(ctx context.Context, arg SetDefinitionStatusParams) (ResourceDefinition, error) {
	row := q.db.QueryRow(ctx, setDefinitionStatus, arg.ID, arg.Status)
	var i ResourceDefinition
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
