// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type ApiClient struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	KeyHash   string    `json:"key_hash"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type ResourceDefinition struct {
	ID          uuid.UUID `json:"id"`
	Key         string    `json:"key"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Icon        string    `json:"icon"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ResourceField struct {
	ID                   uuid.UUID `json:"id"`
	ResourceDefinitionID uuid.UUID `json:"resource_definition_id"`
	Key                  string    `json:"key"`
	Label                string    `json:"label"`
	Hint                 string    `json:"hint"`
	DataType             string    `json:"data_type"`
	Required             bool      `json:"required"`
	IsSecret             bool      `json:"is_secret"`
	SortOrder            int32     `json:"sort_order"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TenantDomain struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Hostname  string    `json:"hostname"`
	CreatedAt time.Time `json:"created_at"`
}

type TenantResource struct {
	ID                   uuid.UUID `json:"id"`
	TenantID             uuid.UUID `json:"tenant_id"`
	ResourceDefinitionID uuid.UUID `json:"resource_definition_id"`
	Status               string    `json:"status"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type TenantResourceValue struct {
	ID               uuid.UUID `json:"id"`
	TenantResourceID uuid.UUID `json:"tenant_resource_id"`
	ResourceFieldID  uuid.UUID `json:"resource_field_id"`
	ValuePlain       *string   `json:"value_plain"`
	ValueCipher      []byte    `json:"value_cipher"`
	Nonce            []byte    `json:"nonce"`
	KeyVersion       *int32    `json:"key_version"`
}
