// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countAPIClients = `-- name: CountAPIClients :one
SELECT count(*)::int AS api_clients FROM api_clients
`

func (q *Queries) CountAPIClients(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countAPIClients)
	var api_clients int32
	err := row.Scan(&api_clients)
	return api_clients, err
}

const countDefinitionsSummary = `-- name: CountDefinitionsSummary :one
SELECT count(*)::int AS definitions,
       (count(*) FILTER (WHERE status = 'active'))::int AS active_definitions
FROM resource_definitions
`

type CountDefinitionsSummaryRow struct {
	Definitions       int32 `json:"definitions"`
	ActiveDefinitions int32 `json:"active_definitions"`
}

func (q *Queries) CountDefinitionsSummary(ctx context.Context) (CountDefinitionsSummaryRow, error) {
	row := q.db.QueryRow(ctx, countDefinitionsSummary)
	var i CountDefinitionsSummaryRow
	err := row.Scan(&i.Definitions, &i.ActiveDefinitions)
	return i, err
}

const createAPIClient = `-- name: CreateAPIClient :one
INSERT INTO api_clients (name, key_hash) VALUES ($1, $2) RETURNING id, name, key_hash, status, created_at
`

type CreateAPIClientParams struct {
	Name    string `json:"name"`
	KeyHash string `json:"key_hash"`
}

func (q *Queries) CreateAPIClient(ctx context.Context, arg CreateAPIClientParams) (ApiClient, error) {
	row := q.db.QueryRow(ctx, createAPIClient, arg.Name, arg.KeyHash)
	var i ApiClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTenantResource = `-- name: CreateTenantResource :one
INSERT INTO tenant_resources (tenant_id, resource_definition_id)
VALUES ($1, $2) RETURNING id, tenant_id, resource_definition_id, status, created_at, updated_at
`

type CreateTenantResourceParams struct {
	TenantID             uuid.UUID `json:"tenant_id"`
	ResourceDefinitionID uuid.UUID `json:"resource_definition_id"`
}

func (q *Queries) CreateTenantResource(ctx context.Context, arg CreateTenantResourceParams) (TenantResource, error) {
	row := q.db.QueryRow(ctx, createTenantResource, arg.TenantID, arg.ResourceDefinitionID)
	var i TenantResource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ResourceDefinitionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenantResource = `-- name: DeleteTenantResource :exec
DELETE FROM tenant_resources WHERE id = $1
`

func (q *Queries) DeleteTenantResource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenantResource, id)
	return err
}

const getAPIClientByHash = `-- name: GetAPIClientByHash :one
SELECT id, name, key_hash, status, created_at FROM api_clients WHERE key_hash = $1
`

func (q *Queries) GetAPIClientByHash(ctx context.Context, keyHash string) (ApiClient, error) {
	row := q.db.QueryRow(ctx, getAPIClientByHash, keyHash)
	var i ApiClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveResourceByTenantAndDefinitionKey = `-- name: GetActiveResourceByTenantAndDefinitionKey :one
SELECT tr.id, tr.tenant_id, tr.resource_definition_id, tr.status, tr.created_at, tr.updated_at
FROM tenant_resources tr
JOIN resource_definitions rd ON rd.id = tr.resource_definition_id
WHERE tr.tenant_id = $1
  AND rd.key = $2
  AND tr.status = 'active'
`

type GetActiveResourceByTenantAndDefinitionKeyParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Key      string    `json:"key"`
}

func (q *Queries) GetActiveResourceByTenantAndDefinitionKey(ctx context.Context, arg GetActiveResourceByTenantAndDefinitionKeyParams) (TenantResource, error) {
	row := q.db.QueryRow(ctx, getActiveResourceByTenantAndDefinitionKey, arg.TenantID, arg.Key)
	var i TenantResource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ResourceDefinitionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIClients = `-- name: ListAPIClients :many
SELECT id, name, key_hash, status, created_at FROM api_clients ORDER BY created_at DESC
`

func (q *Queries) ListAPIClients(ctx context.Context) ([]ApiClient, error) {
	rows, err := q.db.Query(ctx, listAPIClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiClient
	for rows.Next() {
		var i ApiClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyHash,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveResourcesByTenant = `-- name: ListActiveResourcesByTenant :many
SELECT id, tenant_id, resource_definition_id, status, created_at, updated_at FROM tenant_resources WHERE tenant_id = $1 AND status = 'active'
`

func (q *Queries) ListActiveResourcesByTenant(ctx context.Context, tenantID uuid.UUID) ([]TenantResource, error) {
	rows, err := q.db.Query(ctx, listActiveResourcesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantResource
	for rows.Next() {
		var i TenantResource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ResourceDefinitionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverviewTenantCards = `-- name: ListOverviewTenantCards :many
SELECT t.id,
       t.name,
       t.slug,
       t.status,
       coalesce((array_agg(d.hostname ORDER BY d.created_at) FILTER (WHERE d.id IS NOT NULL))[1], '')::text AS primary_host,
       count(DISTINCT d.id)::int AS domain_count,
       count(DISTINCT tr.id) FILTER (WHERE tr.status = 'active')::int AS resource_count
FROM tenants t
LEFT JOIN tenant_domains d ON d.tenant_id = t.id
LEFT JOIN tenant_resources tr ON tr.tenant_id = t.id
GROUP BY t.id
ORDER BY t.name
`

type ListOverviewTenantCardsRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Slug          string    `json:"slug"`
	Status        string    `json:"status"`
	PrimaryHost   string    `json:"primary_host"`
	DomainCount   int32     `json:"domain_count"`
	ResourceCount int32     `json:"resource_count"`
}

func (q *Queries) ListOverviewTenantCards(ctx context.Context) ([]ListOverviewTenantCardsRow, error) {
	rows, err := q.db.Query(ctx, listOverviewTenantCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverviewTenantCardsRow
	for rows.Next() {
		var i ListOverviewTenantCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.PrimaryHost,
			&i.DomainCount,
			&i.ResourceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceValues = `-- name: ListResourceValues :many
SELECT id, tenant_resource_id, resource_field_id, value_plain, value_cipher, nonce, key_version FROM tenant_resource_values WHERE tenant_resource_id = $1
`

func (q *Queries) ListResourceValues(ctx context.Context, tenantResourceID uuid.UUID) ([]TenantResourceValue, error) {
	rows, err := q.db.Query(ctx, listResourceValues, tenantResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantResourceValue
	for rows.Next() {
		var i TenantResourceValue
		if err := rows.Scan(
			&i.ID,
			&i.TenantResourceID,
			&i.ResourceFieldID,
			&i.ValuePlain,
			&i.ValueCipher,
			&i.Nonce,
			&i.KeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantResources = `-- name: ListTenantResources :many
SELECT id, tenant_id, resource_definition_id, status, created_at, updated_at FROM tenant_resources WHERE tenant_id = $1
`

func (q *Queries) ListTenantResources(ctx context.Context, tenantID uuid.UUID) ([]TenantResource, error) {
	rows, err := q.db.Query(ctx, listTenantResources, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantResource
	for rows.Next() {
		var i TenantResource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ResourceDefinitionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAPIClientStatus = `-- name: SetAPIClientStatus :one
UPDATE api_clients SET status = $2 WHERE id = $1 RETURNING id, name, key_hash, status, created_at
`

type SetAPIClientStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetAPIClientStatus(ctx context.Context, arg SetAPIClientStatusParams) (ApiClient, error) {
	row := q.db.QueryRow(ctx, setAPIClientStatus, arg.ID, arg.Status)
	var i ApiClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const setTenantResourceStatus = `-- name: SetTenantResourceStatus :one
UPDATE tenant_resources SET status = $2, updated_at = now()
WHERE id = $1 RETURNING id, tenant_id, resource_definition_id, status, created_at, updated_at
`

type SetTenantResourceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetTenantResourceStatus(ctx context.Context, arg SetTenantResourceStatusParams) (TenantResource, error) {
	row := q.db.QueryRow(ctx, setTenantResourceStatus, arg.ID, arg.Status)
	var i TenantResource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ResourceDefinitionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertResourceValue = `-- name: UpsertResourceValue :one
INSERT INTO tenant_resource_values
  (tenant_resource_id, resource_field_id, value_plain, value_cipher, nonce, key_version)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_resource_id, resource_field_id)
DO UPDATE SET value_plain = EXCLUDED.value_plain,
              value_cipher = EXCLUDED.value_cipher,
              nonce = EXCLUDED.nonce,
              key_version = EXCLUDED.key_version
RETURNING id, tenant_resource_id, resource_field_id, value_plain, value_cipher, nonce, key_version
`

type UpsertResourceValueParams struct {
	TenantResourceID uuid.UUID `json:"tenant_resource_id"`
	ResourceFieldID  uuid.UUID `json:"resource_field_id"`
	ValuePlain       *string   `json:"value_plain"`
	ValueCipher      []byte    `json:"value_cipher"`
	Nonce            []byte    `json:"nonce"`
	KeyVersion       *int32    `json:"key_version"`
}

func (q *Queries) UpsertResourceValue(ctx context.Context, arg UpsertResourceValueParams) (TenantResourceValue, error) {
	row := q.db.QueryRow(ctx, upsertResourceValue,
		arg.TenantResourceID,
		arg.ResourceFieldID,
		arg.ValuePlain,
		arg.ValueCipher,
		arg.Nonce,
		arg.KeyVersion,
	)
	var i TenantResourceValue
	err := row.Scan(
		&i.ID,
		&i.TenantResourceID,
		&i.ResourceFieldID,
		&i.ValuePlain,
		&i.ValueCipher,
		&i.Nonce,
		&i.KeyVersion,
	)
	return i, err
}
