// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAPIClient = `-- name: CreateAPIClient :one
INSERT INTO api_clients (name, key_hash) VALUES ($1, $2) RETURNING id, name, key_hash, status, created_at
`

type CreateAPIClientParams struct {
	Name    string `json:"name"`
	KeyHash string `json:"key_hash"`
}

func (q *Queries) CreateAPIClient(ctx context.Context, arg CreateAPIClientParams) (ApiClient, error) {
	row := q.db.QueryRow(ctx, createAPIClient, arg.Name, arg.KeyHash)
	var i ApiClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTenantResource = `-- name: CreateTenantResource :one
INSERT INTO tenant_resources (tenant_id, resource_definition_id)
VALUES ($1, $2) RETURNING id, tenant_id, resource_definition_id, status, created_at, updated_at
`

type CreateTenantResourceParams struct {
	TenantID             uuid.UUID `json:"tenant_id"`
	ResourceDefinitionID uuid.UUID `json:"resource_definition_id"`
}

func (q *Queries) CreateTenantResource(ctx context.Context, arg CreateTenantResourceParams) (TenantResource, error) {
	row := q.db.QueryRow(ctx, createTenantResource, arg.TenantID, arg.ResourceDefinitionID)
	var i TenantResource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ResourceDefinitionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenantResource = `-- name: DeleteTenantResource :exec
DELETE FROM tenant_resources WHERE id = $1
`

func (q *Queries) DeleteTenantResource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenantResource, id)
	return err
}

const getAPIClientByHash = `-- name: GetAPIClientByHash :one
SELECT id, name, key_hash, status, created_at FROM api_clients WHERE key_hash = $1
`

func (q *Queries) GetAPIClientByHash(ctx context.Context, keyHash string) (ApiClient, error) {
	row := q.db.QueryRow(ctx, getAPIClientByHash, keyHash)
	var i ApiClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIClients = `-- name: ListAPIClients :many
SELECT id, name, key_hash, status, created_at FROM api_clients ORDER BY created_at DESC
`

func (q *Queries) ListAPIClients(ctx context.Context) ([]ApiClient, error) {
	rows, err := q.db.Query(ctx, listAPIClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiClient
	for rows.Next() {
		var i ApiClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyHash,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveResourcesByTenant = `-- name: ListActiveResourcesByTenant :many
SELECT id, tenant_id, resource_definition_id, status, created_at, updated_at FROM tenant_resources WHERE tenant_id = $1 AND status = 'active'
`

func (q *Queries) ListActiveResourcesByTenant(ctx context.Context, tenantID uuid.UUID) ([]TenantResource, error) {
	rows, err := q.db.Query(ctx, listActiveResourcesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantResource
	for rows.Next() {
		var i TenantResource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ResourceDefinitionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceValues = `-- name: ListResourceValues :many
SELECT id, tenant_resource_id, resource_field_id, value_plain, value_cipher, nonce, key_version FROM tenant_resource_values WHERE tenant_resource_id = $1
`

func (q *Queries) ListResourceValues(ctx context.Context, tenantResourceID uuid.UUID) ([]TenantResourceValue, error) {
	rows, err := q.db.Query(ctx, listResourceValues, tenantResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantResourceValue
	for rows.Next() {
		var i TenantResourceValue
		if err := rows.Scan(
			&i.ID,
			&i.TenantResourceID,
			&i.ResourceFieldID,
			&i.ValuePlain,
			&i.ValueCipher,
			&i.Nonce,
			&i.KeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantResources = `-- name: ListTenantResources :many
SELECT id, tenant_id, resource_definition_id, status, created_at, updated_at FROM tenant_resources WHERE tenant_id = $1
`

func (q *Queries) ListTenantResources(ctx context.Context, tenantID uuid.UUID) ([]TenantResource, error) {
	rows, err := q.db.Query(ctx, listTenantResources, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantResource
	for rows.Next() {
		var i TenantResource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ResourceDefinitionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAPIClientStatus = `-- name: SetAPIClientStatus :one
UPDATE api_clients SET status = $2 WHERE id = $1 RETURNING id, name, key_hash, status, created_at
`

type SetAPIClientStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetAPIClientStatus(ctx context.Context, arg SetAPIClientStatusParams) (ApiClient, error) {
	row := q.db.QueryRow(ctx, setAPIClientStatus, arg.ID, arg.Status)
	var i ApiClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const setTenantResourceStatus = `-- name: SetTenantResourceStatus :one
UPDATE tenant_resources SET status = $2, updated_at = now()
WHERE id = $1 RETURNING id, tenant_id, resource_definition_id, status, created_at, updated_at
`

type SetTenantResourceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetTenantResourceStatus(ctx context.Context, arg SetTenantResourceStatusParams) (TenantResource, error) {
	row := q.db.QueryRow(ctx, setTenantResourceStatus, arg.ID, arg.Status)
	var i TenantResource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ResourceDefinitionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertResourceValue = `-- name: UpsertResourceValue :one
INSERT INTO tenant_resource_values
  (tenant_resource_id, resource_field_id, value_plain, value_cipher, nonce, key_version)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_resource_id, resource_field_id)
DO UPDATE SET value_plain = EXCLUDED.value_plain,
              value_cipher = EXCLUDED.value_cipher,
              nonce = EXCLUDED.nonce,
              key_version = EXCLUDED.key_version
RETURNING id, tenant_resource_id, resource_field_id, value_plain, value_cipher, nonce, key_version
`

type UpsertResourceValueParams struct {
	TenantResourceID uuid.UUID `json:"tenant_resource_id"`
	ResourceFieldID  uuid.UUID `json:"resource_field_id"`
	ValuePlain       *string   `json:"value_plain"`
	ValueCipher      []byte    `json:"value_cipher"`
	Nonce            []byte    `json:"nonce"`
	KeyVersion       *int32    `json:"key_version"`
}

func (q *Queries) UpsertResourceValue(ctx context.Context, arg UpsertResourceValueParams) (TenantResourceValue, error) {
	row := q.db.QueryRow(ctx, upsertResourceValue,
		arg.TenantResourceID,
		arg.ResourceFieldID,
		arg.ValuePlain,
		arg.ValueCipher,
		arg.Nonce,
		arg.KeyVersion,
	)
	var i TenantResourceValue
	err := row.Scan(
		&i.ID,
		&i.TenantResourceID,
		&i.ResourceFieldID,
		&i.ValuePlain,
		&i.ValueCipher,
		&i.Nonce,
		&i.KeyVersion,
	)
	return i, err
}
