// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTenantDomain = `-- name: AddTenantDomain :one
INSERT INTO tenant_domains (tenant_id, hostname) VALUES ($1, $2) RETURNING id, tenant_id, hostname, created_at
`

type AddTenantDomainParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Hostname string    `json:"hostname"`
}

func (q *Queries) AddTenantDomain(ctx context.Context, arg AddTenantDomainParams) (TenantDomain, error) {
	row := q.db.QueryRow(ctx, addTenantDomain, arg.TenantID, arg.Hostname)
	var i TenantDomain
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Hostname,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (slug, name) VALUES ($1, $2) RETURNING id, slug, name, status, created_at, updated_at
`

type CreateTenantParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Slug, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :execrows
DELETE FROM tenants WHERE id = $1
`

// Cascades to tenant_domains, tenant_resources and tenant_resource_values (FK ON DELETE CASCADE).
func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTenant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTenant = `-- name: GetTenant :one
SELECT id, slug, name, status, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByHostname = `-- name: GetTenantByHostname :one
SELECT t.id, t.slug, t.name, t.status, t.created_at, t.updated_at FROM tenants t
JOIN tenant_domains d ON d.tenant_id = t.id
WHERE d.hostname = $1
`

func (q *Queries) GetTenantByHostname(ctx context.Context, hostname string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByHostname, hostname)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name, status, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantDomains = `-- name: ListTenantDomains :many
SELECT id, tenant_id, hostname, created_at FROM tenant_domains WHERE tenant_id = $1 ORDER BY hostname
`

func (q *Queries) ListTenantDomains(ctx context.Context, tenantID uuid.UUID) ([]TenantDomain, error) {
	rows, err := q.db.Query(ctx, listTenantDomains, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantDomain
	for rows.Next() {
		var i TenantDomain
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Hostname,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, name, status, created_at, updated_at FROM tenants ORDER BY name
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTenantDomain = `-- name: RemoveTenantDomain :exec
DELETE FROM tenant_domains WHERE id = $1
`

func (q *Queries) RemoveTenantDomain(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeTenantDomain, id)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants SET name = $2, slug = $3, status = $4, updated_at = now()
WHERE id = $1 RETURNING id, slug, name, status, created_at, updated_at
`

type UpdateTenantParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Slug   string    `json:"slug"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Status,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
