{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tenancit.fullname" . }}
  {{- if not .Values.ingress.tlsSecretName }}
  annotations:
    {{- if and .Values.personal.enabled .Values.personal.createAcmeIssuer }}
    cert-manager.io/issuer: {{ printf "%s-letsencrypt" (include "tenancit.fullname" .) | quote }}
    {{- else }}
    cert-manager.io/cluster-issuer: {{ .Values.public.tlsClusterIssuer | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts: [{{ .Values.public.host | quote }}]
      secretName: {{ .Values.ingress.tlsSecretName | default (printf "%s-tls" (include "tenancit.fullname" .)) }}
  rules:
    - host: {{ .Values.public.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: Prefix
            backend:
              service: { name: {{ include "tenancit.fullname" . }}, port: { name: http } }
{{- if .Values.personal.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tenancit.fullname" . }}-oidc
  annotations:
    {{- if .Values.personal.createAcmeIssuer }}
    cert-manager.io/issuer: {{ printf "%s-letsencrypt" (include "tenancit.fullname" .) | quote }}
    {{- else }}
    cert-manager.io/cluster-issuer: {{ .Values.public.tlsClusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts: [{{ .Values.public.oidcHost | quote }}]
      secretName: {{ include "tenancit.fullname" . }}-oidc-tls
  rules:
    - host: {{ .Values.public.oidcHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: {{ include "tenancit.fullname" . }}-dex, port: { name: http } }
{{- end }}
{{- end }}
