image:
  repository: ghcr.io/djalmajr/tenancit
  digest: ""
  pullPolicy: IfNotPresent
imagePullSecrets: []

replicaCount: 2
existingSecret: tenancit-runtime

public:
  host: tenancit.example.invalid
  oidcHost: tenancit-id.example.invalid
  tlsClusterIssuer: letsencrypt-prod

oidc:
  issuerPath: /dex
  clientId: tenancit
  roleClaim: email
  roleMappings: '{"admin@tenancit.local":"security_admin"}'

resources:
  app:
    requests: { cpu: 50m, memory: 96Mi }
    limits: { cpu: 500m, memory: 256Mi }
  jobs:
    requests: { cpu: 25m, memory: 64Mi }
    limits: { cpu: 250m, memory: 192Mi }

personal:
  enabled: false
  createAcmeIssuer: true
  acmeEmail: admin@example.invalid
  storageClassName: local-path
  postgresStorage: 5Gi
  dexStorage: 256Mi
  postgresImage: postgres@sha256:16bc17c64a573ef34162af9298258d1aec548232985b33ed7b1eac33ba35c229
  valkeyImage: valkey/valkey@sha256:cfe71288f087704b06be45e270afa7a2abbf820093d6b11a23762081f5ff321d
  dexImage: ghcr.io/dexidp/dex@sha256:5d0656fce7d453c0e3b2706abf40c0d0ce5b371fb0b73b3cf714d05f35fa5f86
  traefikNamespace: traefik
